# Generated by Django 4.1.2 on 2023-11-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_starting_price_auction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='imageurl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
